name: zebra
description: "A Flutter SSH client with SFTP and terminal support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.28
  provider: ^6.1.2
  dartssh2: ^2.8.2
  xterm: ^4.0.0
  file_picker: ^8.1.7
  path: ^1.9.0
  shared_preferences: ^2.3.4
  desktop_drop: ^0.5.0
  archive: ^3.6.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0
  markdown: ^7.3.0
  window_manager: ^0.5.2
  contextmenu: ^3.0.0
  http: ^1.2.0
  xml: ^6.5.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
